# Generated by Django 5.0.6 on 2024-05-20 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_joblising_savejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='savejob',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
