# Generated by Django 5.0.6 on 2024-05-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_savejob_saved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savejob',
            name='candidate',
        ),
    ]
