# Generated by Django 5.0.6 on 2024-05-20 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_savejob_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='savejob',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
