# Generated by Django 5.0.6 on 2024-05-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_savejob_candidate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobLising',
            new_name='JobListing',
        ),
    ]
